name: .NET Core

on:
  repository_dispatch:
    types: [testing]
  #push:
    #branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - run: 'echo "testType: ${{ github.event.client_payload.testType }}"'
    - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Test echo
      run: echo hello1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack libraries
      run: dotnet pack --no-build --configuration Release -o  ${{ github.workspace }}\nuget-packages\
    - name: Publish nuget packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: ${{ github.workspace }}\nuget-packages
