name: .NET Core

on:
  push:
    branches: [ testbuild ]
  pull_request:
    branches: [ testbuild ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --logger trx --results-directory $GITHUB_WORKSPACE/artifacts/ /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:MergeWith=$GITHUB_WORKSPACE/artifacts/coverage.cobertura.merged.xml  /p:CoverletOutput=$GITHUB_WORKSPACE/artifacts/
    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ${{ github.workspace }}/artifacts
    - name: Pack libraries
      run: dotnet pack --no-build --configuration Release -o  $GITHUB_WORKSPACE/nuget-packages/
    - name: Publish nuget packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: ${{ github.workspace }}/nuget-packages
    - name: Publish to nuget.org
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY}} --source https://api.nuget.org/v3/index.json
      
